services:
  - type: web
    name: jarvis
    repo: https://github.com/rajachatterjee1993-hue/Jarvis.git
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: RENDER_APP_NAME
        value: "jarvis"
      - key: RENDER_API
        value: "rnd_JJiUXcvxvwRduIST8s2Ggo1llCWz"
      - key: SESSION_ID
        value: "Jarvis_95u0_4w15_v0v0_wy52_w415_0vz0_w0zw_v427"
      - key: DATABASE_URL
        value: "postgresql://gourab_debnath_user:0J5k5PJsRL8kCpHnoUJgiW87bzGSbspj@dpg-d92ens7avr4c7387dru0-a.oregon-postgres.render.com/gourab_debnath"
      - key: HANDLER
        value: "!"
      - key: WORK_TYPE
        value: "private"
      - key: ERROR_MSG
        value: "true"
      - key: BOT_INFO
        value: "ᴊᴀʀᴠɪꜱ;ʟᴏᴋɪ-xᴇʀ;https://graph.org/file/f23f574f13baaf790f250.jpg"
      - key: AUDIO_DATA
        value: "ᴊᴀʀᴠɪꜱ;ʟᴏᴋɪ-xᴇʀ;https://graph.org/file/76a1d2fe74ba5e5643e16.jpg"
      - key: MEDIA_DATA
        value: "ʟɪꜱᴛᴍᴇɴᴜ;ᴊᴀʀᴠɪꜱ-ᴍᴅ;https://graph.org/file/46ad7e1ba38c82aee6c0d.jpg"
      - key: STICKER_PACKNAME
        value: "ᴃ𝗍／𝗐𝗈𝗋𝗅𝗗𐌌ꙮ⍆ꕶ🌟🐊❳"
      - key: SUDO
        value: "917025673121"
      - key: WARN_COUNT
        value: "3"
      - key: ALLWAYS_ONLINE
        value: "false"
      - key: READ_MSG
        value: "false"
      - key: SAVE_STATUS
        value: "false"
      - key: STATUS_VIEW
        value: "false"
      - key: REJECT_CALL
        value: "false"
