services:
  - type: web
    name: jarvis
    repo: https://github.com/rajachatterjee1993-hue/Jarvis.git
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: RENDER_APP_NAME
        value: "Jarvis"
      - key: RENDER_API
        value: "rnd_0z0ahsuIbQW9MoZ8PBEOVYWgbWrz"
      - key: SESSION_ID
        value: "Jarvis_z98v_81xy_6117_5308_0505_4v55_2x8u_w647"
      - key: DATABASE_URL
        value: "postgresql://puja_roy_user:DIEe6RPuGfeWgHJzofnBOGDSRfyIyaYO@dpg-d97n8t58nd3s73e3dgr0-a.oregon-postgres.render.com/puja_roy"
      - key: HANDLER
        value: "!"
      - key: WORK_TYPE
        value: "private"
      - key: ERROR_MSG
        value: "true"
      - key: BOT_INFO
        value: "ᴊᴀʀᴠɪꜱ;ʟᴏᴋɪ-xᴇʀ;https://graph.org/file/f23f574f13baaf790f250.jpg"
      - key: AUDIO_DATA
        value: "ᴊᴀʀᴠɪꜱ;ʟᴏᴋɪ-xᴇʀ;https://graph.org/file/76a1d2fe74ba5e5643e16.jpg"
      - key: MEDIA_DATA
        value: "ʟɪꜱᴛᴍᴇɴᴜ;ᴊᴀʀᴠɪꜱ-ᴍᴅ;https://graph.org/file/46ad7e1ba38c82aee6c0d.jpg"
      - key: STICKER_PACKNAME
        value: "ᴃ𝗍／𝗐𝗈𝗋𝗅𝗗𐌌ꙮ⍆ꕶ🌟🐊❳"
      - key: SUDO
        value: "917025673121"
      - key: WARN_COUNT
        value: "3"
      - key: ALLWAYS_ONLINE
        value: "false"
      - key: READ_MSG
        value: "false"
      - key: SAVE_STATUS
        value: "false"
      - key: STATUS_VIEW
        value: "false"
      - key: REJECT_CALL
        value: "false"
